update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,14 +22,13 @@ jobs:
         env:
           KAFKA_BROKER_ID: 1
           KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
-          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT://localhost:9092
+          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
           KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
           KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
           KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
           KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
         ports:
           - 9092:9092
-        options: --network-alias kafka
 
       mysql_test:
         image: mysql:8.0
@@ -75,19 +74,10 @@ jobs:
             sleep 5
           done
 
-      # - name: Wait for Kafka to be Ready
-      #   run: |
-      #     echo "Waiting for Kafka to be ready..."
-      #     for i in {1..5}; do
-      #      nc -zv localhost 9092 && break
-      #      echo "Kafka not ready yet..."
-      #      sleep 5
-      #     done
       - name: Debug Kafka Connection
         run: |
           echo "Testing Kafka connection..."
-          curl kafka:9092 || echo "Connection to Kafka failed"
-          echo "Connection to Kafka successful"
+          nc -zv localhost 9092 || echo "Connection to Kafka failed"
 
       - name: Run Tests
         env:
