update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,21 +12,6 @@ jobs:
     name: Test and SonarCloud Scan
     runs-on: ubuntu-latest
     services:
-      zookeeper:
-        image: wurstmeister/zookeeper:latest
-        ports:
-          - 2181:2181
-
-      kafka:
-        image: wurstmeister/kafka:latest
-        env:
-          KAFKA_BROKER_ID: 1
-          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
-          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
-          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
-        ports:
-          - 9092:9092
-
       mysql_test:
         image: mysql:8.0
         env:
@@ -43,6 +28,13 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Install Docker Compose
+        run: sudo apt-get install -y docker-compose  # Ensure docker-compose is available
+  
+      - name: Set up Docker Compose
+        run: docker-compose -f docker-compose-kafka.yml up -d
+        
+
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
@@ -57,33 +49,25 @@ jobs:
         run: |
           echo "Waiting for MySQL to be ready..."
           for i in {1..30}; do
-            mysqladmin ping -h mysql_test -P 3306 -u user --password=VERY_SECURE_PASSWORD && break
+            mysqladmin ping -h 127.0.0.1 -P 3306 -u user --password=VERY_SECURE_PASSWORD && break
             echo "MySQL not ready yet..."
-            sleep 5
-          done
-
-      - name: Wait for Zookeeper to be Ready
-        run: |
-          echo "Waiting for Zookeeper to be ready..."
-          for i in {1..30}; do
-            nc -zv zookeeper 2181 && break
-            echo "Zookeeper not ready yet..."
             sleep 5
           done
 
       - name: Debug Kafka Connection
         run: |
           echo "Testing Kafka connection..."
-          nc -zv kafka 9092 || echo "Connection to Kafka failed"
+          nc -zv localhost 9092 || echo "Connection to Kafka failed"
 
       - name: Run Tests
         env:
           DB_USER: user
           DB_PASSWORD: VERY_SECURE_PASSWORD
-          DB_HOST: mysql_test
+          DB_HOST: localhost
           DB_NAME: landlord_db
           DB_PORT: 3306
-          KAFKA_BOOTSTRAP_SERVERS: kafka:9092
+          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
+          ENV: development
         run: |
           pytest --cov=./ --cov-report=xml
 
